baseURL = '/'
languageCode = 'en-us'
title = 'Research Notes'
theme = "m10c"
googleAnalytics = ""

rssLimit = 20
copyright = "Martin Stoynov"

[author]
  name = "Martin Stoynov"

[params]
  author = "Martin Stoynov"
  description = "A Zettelkasten-style digital garden of evolving research notes."
  favicon = "favicon.ico"
  avatar = "avatar.jpg"

[[menu.main]]
  identifier = "root"
  name = "Notes"
  url = "/"

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

[[menu.main]]
  identifier = "posts"
  name = "Notes"
  url = "/posts/"

[[params.social]]
  icon = "github"
  name = "Github"
  url = "https://github.com/martinstnv"

[[params.social]]
  icon = "linkedin"
  name = "Linkedin"
  url = "https://linkedin.com/in/martinstnv"

[[params.social]]
  icon = "brand-mastodon"
  name = "Infosec Exchanges"
  url = "https://infosec.exchange/@martinstnv"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
